config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :movies
  root :to => redirect('/movies')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ActiveRecord::Base
    validates :title, presence: true, uniqueness: true
    validates :rating, presence: true
    validates :release_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    session[:sort] = params[:sort] if params[:sort]
    session[:direction] = params[:direction] if params[:direction]

    # Use session params if no new params are passed
    @sort_column = session[:sort] || 'title'
    @sort_direction = session[:direction] || 'asc'

    puts @sort_column
    puts @sort_direction
    @movies = Movie.order("#{@sort_column} #{@sort_direction}")
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        if @movie.errors[:title].include?("has already been taken")
          flash.now[:alert] = "A movie with this title already exists."
        end
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy!

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :rating, :description, :release_date)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def body_class
        case
        when controller_name == 'movies' && action_name == 'index'
          'index-page'
        when controller_name == 'movies' && action_name == 'show'
          'show-page'
        else
          'default-page'
        end
      end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rottenpotatoes" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="<%= body_class %>">
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<div class="form-submit-container" style="padding-left: 12%;">
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="background-color: #ffd3d365;">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block;" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :release_date, style: "display: block" %>
    <%= form.text_field :release_date %>
  </div>

  <div>
    <%= form.submit class: 'btn-form' %>
  </div>
<% end %>
</div>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>" class="movie-details">
  <p >
    <h2 ><%= movie.title %></h2>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= movie.rating %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= movie.description %>
  </p>

  <p>
    <strong>Release date:</strong>
    <%= movie.release_date %>
  </p>

</div>

app/views/movies/edit.html.erb
<% content_for :title, "Editing movie" %>

<h1 style="text-align:center">Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div class="btn-group">
  <%= link_to "Show this movie", @movie ,class: 'btn-custom' %>
  <%= link_to "Back to movies", movies_path(sort: session[:sort], direction: session[:direction]), class: 'btn-custom' %>
</div>

app/views/movies/index.html.erb
<h2 style="font-family: Arial, Helvetica, sans-serif;">MOVIES</h2>

<table class="table table-striped col-md-12" id="movies">
  <thead>
    <tr>
      <th class="<%= 'highlight-asc' if params[:sort] == 'title' && params[:direction] == 'asc' %> <%= 'highlight-desc' if params[:sort] == 'title' && params[:direction] == 'desc' %>">
        Movie Title 
        <%= link_to "#{params[:sort] == 'title' ? (params[:direction] == 'asc' ? '↑' : '↓') : '↕'}", movies_path(sort: 'title', direction: params[:direction] == 'asc' ? 'desc' : 'asc'), data: { turbo: "false" } %>
      </th>
      <th class="<%= 'highlight-asc' if params[:sort] == 'rating' && params[:direction] == 'asc' %> <%= 'highlight-desc' if params[:sort] == 'rating' && params[:direction] == 'desc' %>">
        Rating 
        <%= link_to "#{params[:sort] == 'rating' ? (params[:direction] == 'asc' ? '↑' : '↓') : '↕'}", movies_path(sort: 'rating', direction: params[:direction] == 'asc' ? 'desc' : 'asc'), data: { turbo: "false" } %>
      </th>
      <th class="<%= 'highlight-asc' if params[:sort] == 'release_date' && params[:direction] == 'asc' %> <%= 'highlight-desc' if params[:sort] == 'release_date' && params[:direction] == 'desc' %>">
        Release Date 
        <%= link_to "#{params[:sort] == 'release_date' ? (params[:direction] == 'asc' ? '↑' : '↓') : '↕'}", movies_path(sort: 'release_date', direction: params[:direction] == 'asc' ? 'desc' : 'asc'), data: { turbo: "false" } %>
      </th>
      <th>More Info</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td class="<%= 'highlight-column-asc' if params[:sort] == 'title' && params[:direction] == 'asc' %> <%= 'highlight-column-desc' if params[:sort] == 'title' && params[:direction] == 'desc' %>">
          <%= movie.title %>
        </td>
        <td  class="<%= 'highlight-column-asc' if params[:sort] == 'rating' && params[:direction] == 'asc' %> <%= 'highlight-column-desc' if params[:sort] == 'rating' && params[:direction] == 'desc' %>">
          <%= movie.rating %>
        </td>
        <td  class="<%= 'highlight-column-asc' if params[:sort] == 'release_date' && params[:direction] == 'asc' %> <%= 'highlight-column-desc' if params[:sort] == 'release_date' && params[:direction] == 'desc' %>">
          <%= movie.release_date %>
        </td>
        <td><%= link_to 'Show movie', movie_path(movie), class: 'btn-show' %> <%= link_to 'Edit movie', edit_movie_path(movie), class: 'btn-edit' %> <%= link_to 'Delete movie', movie, method: :delete, class: 'btn-delete' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add new movie', new_movie_path, class: 'btn-custom' %>

app/views/movies/new.html.erb
<div >
<% content_for :title, "New movie" %>

<h1 style="text-align:center">New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div style="padding-left: 12%;">
  <%= link_to "Back to movies", movies_path(sort: session[:sort], direction: session[:direction]), class: 'btn-custom' %>
</div>
</div>

app/views/movies/show.html.erb
<div>
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div class="btn-group">
 <%= link_to "Back to movies", movies_path(sort: session[:sort], direction: session[:direction]), class: 'btn-show' %>
 <%= button_to "Destroy this movie", @movie, method: :delete, class: 'btn-delete' %>
</div>
</div>